In [1]:
import requests
import bs4
import pandas as pd
import datetime

In [2]:
import pymysql 
from sqlalchemy import create_engine

In [3]:
# Selenium 셀레늄으로 Chrome 웹 브라우저 띄우기 

from selenium import webdriver

from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

chromeOption = Options()

chromeOption.add_argument("window-size=1920X1080")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install() ),
                          options=chromeOption)

In [4]:
# 웹페이지 이동하기
targetUrl = "https://www.naver.com/"
driver.get(targetUrl)

In [5]:
# 버튼 클릭하기 

BtnXpath = '//*[@id="NM_FAVORITE"]/div[1]/ul[2]/li[2]/a'
EconomyBtn = '/html/body/section/header/div[2]/div/div/div[1]/div/div/ul/li[3]/a/span'
from selenium.webdriver.common.by import By

driver.find_element(By.XPATH, BtnXpath).click()
driver.implicitly_wait(3)

In [6]:
driver.find_element(By.XPATH, EconomyBtn).click()

In [7]:
# 수집한 날짜 정보 저장
currentDate=datetime.datetime.now()

timeKey = currentDate.strftime("%Y_%m_%d")

In [8]:
# 페이지 소스받아와서 html로 변경해주기
textObj = driver.page_source

htmlObj=bs4.BeautifulSoup(textObj, "html.parser")


# 네이버 경제면 헤드라인 뽑아오기 
mainContent = htmlObj.find(id = "main_content")


mainContentInfo =mainContent.findAll(name = "li", attrs = {"class" : "cluster_item"})
mainContentInfo[0].find(attrs = {"class" :"cluster_text"}).find (name ="a")

headlineInfoList = []

for i in range (0, len(mainContentInfo)) :
    try : 
        headline = mainContentInfo[i].find(attrs = {"class" :"cluster_text"}).find (name ="a")
        headlineInfoList.append(headline)
    except Exception as e : 
        print(e)

headLineList =[]

for i in range(0, len(headlineInfoList)) :    
    mainHead = headlineInfoList[i].text                
    url = headlineInfoList[i].attrs['href'] 
    
    headLineList.append([mainHead,url] )

newHeadlineData = pd.DataFrame (headLineList)
newHeadlineData.columns = ["헤드라인", "URL 링크"]
newHeadlineData

,헤드라인,URL 링크
0,"LG화학, 새만금에 1.2조 투자… 매년 전기차 100만대 ‘전구체’ 생산",https://n.news.naver.com/mnews/article/366/000...
1,"LG화학, 새만금 전구체 공장 MOU 체결",https://n.news.naver.com/mnews/article/015/000...
2,"LG화학 ""美테네시에 배터리소재 거점 구축""",https://n.news.naver.com/mnews/article/009/000...
3,"이차전지 1조2천억원 투자 유치, 김관영 전북지사 ""특화단지 성큼""",https://n.news.naver.com/mnews/article/079/000...
4,"테슬라, 실적발표 직전 美서 또 가격인하…마진율 20% 유지 여부 관심",https://n.news.naver.com/mnews/article/374/000...
5,‘가격 전쟁’ 테슬라 1분기 성적에 쏠린 눈,https://n.news.naver.com/mnews/article/016/000...
6,"테슬라, 가격내려 더많이 팔았지만…순이익 전년比 24% 급감(종합)",https://n.news.naver.com/mnews/article/018/000...
7,"순익 크게 하락한 1분기 성적표… 테슬라, 시간외 6% 하락 [美 증시 & IT]",https://n.news.naver.com/mnews/article/138/000...
8,‘유럽판 칩스법’ 합의…EU도 반도체 전쟁 참전,https://n.news.naver.com/mnews/article/025/000...
9,문 잠그는 EU…반도체법·탄소국경세에 韓기업 긴장,https://n.news.naver.com/mnews/article/008/000...
10,미국 이어 EU도 반도체법 합의… “2030년 세계점유율 2배 이상 확대”,https://n.news.naver.com/mnews/article/021/000...
11,"유럽도 반도체 전쟁 참전 ""62조 투자해 점유율 20%""",https://n.news.naver.com/mnews/article/009/000...
12,남방큰돌고래에 과도하게 접근하면 과태료 최대 200만 원,https://n.news.naver.com/mnews/article/052/000...
13,남방큰돌고래를 보호하라... 관광 때 50m 이내 접근하면 과태료 200만원,https://n.news.naver.com/mnews/article/023/000...
14,"""피해자에 우선매수권…소송비도 지원""(종합)",https://n.news.naver.com/mnews/article/018/000...
15,인천 '전세사기' 피해 2479가구…20일부터 경매 6개월 이상 유예,https://n.news.naver.com/mnews/article/015/000...
16,"대한상의, SK·신한은행·이디야커피 손잡고 위기청소년 돕기 나서",https://n.news.naver.com/mnews/article/025/000...
17,"‘위기 청소년’ 위해… 재계, 23억대 나눔 보따리",https://n.news.naver.com/mnews/article/005/000...
18,"대우조선해양, KDDX사업 불공정 수주 국민감사청구",https://n.news.naver.com/mnews/article/002/000...
19,"대우조선해양, KDDX 사업 수주에 대한 국민감사청구 제기",https://n.news.naver.com/mnews/article/016/000...
20,"광양국가산단, 국내 첫 '융합산단' 명찰 단다",https://n.news.naver.com/mnews/article/015/000...
21,스마트 산단에 광양·신평장림·한국수출산단 추가 지정,https://n.news.naver.com/mnews/article/016/000...
22,"현대차·기아, 1분기 유럽 판매량 4.7% 증가… 전기차 판매는 줄어",https://n.news.naver.com/mnews/article/022/000...
23,"현대차·기아, 1분기 유럽 판매량 4.7%↑…전기차는 20%↓",https://n.news.naver.com/mnews/article/015/000...
24,"삼성카드, CJ올리브네트웍스 등과 ‘데이터 동맹’[Biz & Now]",https://n.news.naver.com/mnews/article/025/000...
25,삼성카드 등 5개사 ‘데이터 얼라이언스’ 제휴,https://n.news.naver.com/mnews/article/014/000...
26,"""전세사기·깡통주택 무서워""…서울 빌라 전세 비중 54% '역대 최소'",https://n.news.naver.com/mnews/article/003/001...
27,전세사기 걱정에…1분기 서울 빌라 전세 비중 역대 최저,https://n.news.naver.com/mnews/article/374/000...
28,"""배째라는 병원·의사·실장에 골머리 앓는 소비자""…소비자원, 병원 선납 신중 당부",https://n.news.naver.com/mnews/article/014/000...
29,병원비 선납 피해 급증… 소비자원 '주의보' 발령,https://n.news.naver.com/mnews/article/277/000...
30,만원짜리 점심을 8천원에?…지역사랑하면 돈 번다?,https://n.news.naver.com/mnews/hotissue/articl...
31,돈만 받고 신용카드 해지하면 불이익 없을까요?,https://n.news.naver.com/mnews/hotissue/articl...
32,10+,/main/read.naver?oid=374&aid=0000331415&m_view...
33,"500만원 넘는 명품, 국내서 사는 게 낫다?",https://n.news.naver.com/mnews/hotissue/articl...

In [9]:
newHeadlineData["TIME_KEY"] = timeKey # 수집시간 정보 데이터에 추가하기

columnArrange=["TIME_KEY", "URL 링크", "헤드라인"]

newHeadlineData = newHeadlineData.loc[:,columnArrange ]

In [10]:
# DB 커넥션 열기
inId = "root"
inPw = "0000"
inIp = "127.0.0.1"
inPort ="3306"
inDbName = "web"
engine_mariadb = create_engine('mysql+pymysql://{}:{}@{}:{}/{}'.format(inId,inPw,inIp,inPort,inDbName))
resultname = "KOPO_HEADLINENEWS"
newHeadlineData.to_sql(name=resultname, con = engine_mariadb , if_exists = "append" , index = False) # if_exists = append로 있는 정보 계속 더하기

C:\Users\SMART-10\anaconda3\lib\site-packages\pandas\io\sql.py:1666: UserWarning: The provided table name 'KOPO_HEADLINENEWS' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  warnings.warn(msg, UserWarning)

34

In [13]:
pd.read_sql_query("select * from KOPO_HEADLINENEWS", con=engine_mariadb) # mariaDB sql로 데이터 저장

,TIME_KEY,URL 링크,헤드라인
0,2023_04_14,https://n.news.naver.com/mnews/article/055/000...,"'에스디컬렉션' 소비자 피해주의보 발령…""배송 · 환급 지연"""
1,2023_04_14,/main/read.naver?oid=081&aid=0003353834&mid=sh...,10이상+
2,2023_04_14,https://n.news.naver.com/mnews/article/437/000...,"""샤넬백 싸다 했더니""… 명품구매대행 '에스디컬렉션' 소비자 피해주의보"
3,2023_04_14,https://n.news.naver.com/mnews/article/001/001...,'에스디컬렉션' 소비자 피해주의보…명품 판매하고 배송지연
4,2023_04_14,https://n.news.naver.com/mnews/article/421/000...,전세사기 피해자도 기한 연장 된다…은행권 공동 대응 나서
...,...,...,...
132,2023_04_20,https://n.news.naver.com/mnews/article/277/000...,병원비 선납 피해 급증… 소비자원 '주의보' 발령
133,2023_04_20,https://n.news.naver.com/mnews/hotissue/articl...,만원짜리 점심을 8천원에?…지역사랑하면 돈 번다?
134,2023_04_20,https://n.news.naver.com/mnews/hotissue/articl...,돈만 받고 신용카드 해지하면 불이익 없을까요?
135,2023_04_20,/main/read.naver?oid=374&aid=0000331415&m_view...,10+
136,2023_04_20,https://n.news.naver.com/mnews/hotissue/articl...,"500만원 넘는 명품, 국내서 사는 게 낫다?"

In [14]:
newHeadlineData.to_csv("./news.csv", encoding="ms949") #엑셀파일로 저장 - 자동화

In [15]:
# #미래 수집데이터
# newData = pd.DataFrame( [["2023_04_15", "htttp:....", "비피해조심"]], columns = newHeadlineData.columns )
# #미래 데이터 저장
# newData.to_sql(name=resultname, con = engine_mariadb , if_exists = "append" , index = False)